### ISSUE TITLE
Unable to include Julia in Jupyter-LLM image due to build issue

### ISSUE THREAD

**Issue by mattprintz** [DARPA-ASKEM/beaker-kernel#1]
It appears that the github actions build server is running out of memory while trying to precompile the Julia sciml stack during the docker build.

As we aren't yet using Julia with the LLM I have commented out the install and pre-compilation section of the Dockerfile.

**Comment by fivegrant** [comment]
closing because we're now using Julia in the image. Feel free to reopen if it's still an issue
