### ISSUE TITLE
New Mode: Decapode Configure

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/beaker-kernel#22]
When creating a Decapode, we only receive a model which is not enough for a simulation. A notebook mode where a Decapode is loaded in then  some mesh and dimensionality code is written and exported as a configuration

**Comment by brandomr** [comment]
The simulation won't be occurring in Beaker, just composition but I can see how until there are Terarium UI components for generating the configuration and/or mesh management this could be useful. I suppose one option would be to have an "operator" that is a Decapodes/Julia "model configuration" operator which would be, for the time being, a code interface. This is a good discussion point for next week to determine if it's needed or a priority. Until there's some resolution / decision we could hold off on this one.
