### ISSUE TITLE
Experimental code generation

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/beaker-kernel#41]
This issue is related to code generation using obscure/new modeling and simulation frameworks that won't be as well understood as, say, Pandas 🙄 

For example, if given the entirety of [`Oceananigans.jl`](https://clima.github.io/OceananigansDocumentation/stable/) documentation and a [paper](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/reporting/scenarios/Antarctic%20Ice%20Shelf/paper.pdf) whose model/simulation relies on `Oceananigans`, can GPT-4 recreate the [simulation code referenced in the paper](https://github.com/arnscheidt/antarctic-meltwater-settling-depth/blob/main/les_3d.jl) ("ground truth").

> Note this example may not be ideal since the code uses outdated `Oceananigans.jl` paradigms.

Additional areas to explore might be:

- whether the whole code base for the library can be ingested into context and/or used as part of a RAG approach
- whether stackexchange or other user provided forums can be leveraged for assistance in the generation process (e.g. [GH discussions](https://github.com/CliMA/Oceananigans.jl/discussions) or [GH wiki](https://github.com/CliMA/Oceananigans.jl/wiki)

**Comment by brandomr** [comment]
An update to this issue--we are now shifting focus to look at auto generation of model configurations (e.g. MITGCM or GraphCast)

**Comment by ryanholtschneider2** [comment]
Extracting configuration, output and run command info working pretty well on auto-config. Take a look at https://github.com/DARPA-ASKEM/auto-config for a demo video, code and a system diagram
